"""
r3con v7.0 - JIRA & DefectDojo & Integrations PRO
Export findings to JIRA, DefectDojo, GitHub Issues, Slack
"""
from __future__ import annotations
from typing import Dict, List, Any
import json
from datetime import datetime

class JIRAExporter:
    """JIRA exporter PRO."""

    def __init__(self, jira_url: str = None, username: str = None, api_token: str = None, project_key: str = "SEC"):
        self.jira_url = jira_url
        self.username = username
        self.api_token = api_token
        self.project_key = project_key

    def generate_jira_issues(self, findings: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """Generate JIRA issues from findings."""
        issues = []

        for finding in findings[:100]:
            severity = finding.get("severity", "MEDIUM")
            # Map severity to JIRA priority
            priority_map = {
                "CRITICAL": "Highest",
                "HIGH": "High",
                "MEDIUM": "Medium",
                "LOW": "Low",
                "INFO": "Lowest",
            }

            issue = {
                "fields": {
                    "project": {"key": self.project_key},
                    "summary": f"[{severity}] {finding.get('type','Vulnerability')} - {finding.get('file','unknown')}",
                    "description": self._format_description(finding),
                    "issuetype": {"name": "Bug"},
                    "priority": {"name": priority_map.get(severity, "Medium")},
                    "labels": ["r3con", "security", finding.get("type","").lower().replace(" ", "-")[:30], severity.lower()],
                }
            }

            # Add custom fields for security
            issue["fields"]["customfield_security_severity"] = severity
            issue["fields"]["customfield_cve"] = finding.get("cve", "")
            issue["fields"]["customfield_file"] = finding.get("file", "")
            issue["fields"]["customfield_line"] = finding.get("line", 0)

            issues.append(issue)

        return issues

    def _format_description(self, finding: Dict[str, Any]) -> str:
        desc = f"""h2. Vulnerability Details

*Type:* {finding.get('type','Unknown')}
*Severity:* {finding.get('severity','MEDIUM')}
*File:* {finding.get('file','unknown')}:{finding.get('line','')}
*CWE:* {finding.get('cwe','N/A')}
*CVSS:* {finding.get('cvss','N/A')}

h3. Description
{finding.get('description','No description')}

h3. Recommendation
{finding.get('recommendation','Review code')}

h3. Evidence
{{code}}
{finding.get('evidence', {}).get('code','') if isinstance(finding.get('evidence'), dict) else finding.get('code','')[:500]}
{{code}}

h3. MITRE ATT&CK
{', '.join(finding.get('mitre', []) or ['N/A'])}

h3. Generated by r3con v7.0
*Date:* {datetime.now().isoformat()}
"""
        return desc

    def export_json(self, findings: List[Dict[str, Any]], output_path: str = None) -> Dict[str, Any]:
        """Export as JIRA JSON."""
        issues = self.generate_jira_issues(findings)

        result = {
            "status": "ok",
            "engine": "jira_exporter",
            "project": self.project_key,
            "total_issues": len(issues),
            "issues": issues[:20],  # Preview
        }

        if output_path:
            try:
                with open(output_path, 'w') as f:
                    json.dump({"issues": issues}, f, indent=2)
                result["output_path"] = output_path
            except Exception as e:
                result["export_error"] = str(e)[:500]

        return result

    def push_to_jira(self, findings: List[Dict[str, Any]]) -> Dict[str, Any]:
        """Push to JIRA via API (requires credentials)."""
        if not self.jira_url or not self.username or not self.api_token:
            return {"status": "error", "error": "Missing JIRA credentials (url, username, api_token)"}

        try:
            import requests
            issues = self.generate_jira_issues(findings)
            created = []

            for issue in issues[:10]:  # Limit to 10 for safety
                url = f"{self.jira_url}/rest/api/2/issue"
                resp = requests.post(url, json=issue, auth=(self.username, self.api_token), headers={"Content-Type": "application/json"}, timeout=10)
                if resp.status_code == 201:
                    created.append(resp.json())
                else:
                    created.append({"error": resp.text[:500], "status_code": resp.status_code})

            return {"status": "ok", "created": created, "total": len(created)}

        except ImportError:
            return {"status": "error", "error": "requests not installed"}
        except Exception as e:
            return {"status": "error", "error": str(e)[:500]}

class DefectDojoExporter:
    """DefectDojo exporter PRO."""

    def __init__(self, dojo_url: str = None, api_key: str = None):
        self.dojo_url = dojo_url
        self.api_key = api_key

    def generate_findings(self, findings: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """Generate DefectDojo findings."""
        dojo_findings = []

        for finding in findings[:100]:
            dojo_finding = {
                "title": f"[{finding.get('severity','MEDIUM')}] {finding.get('type','Vulnerability')}",
                "description": finding.get("description", ""),
                "severity": finding.get("severity", "Medium"),
                "numerical_severity": {"CRITICAL": "S0", "HIGH": "S1", "MEDIUM": "S2", "LOW": "S3"}.get(finding.get("severity", "MEDIUM"), "S2"),
                "file_path": finding.get("file", ""),
                "line": finding.get("line", 0),
                "cwe": int(finding.get("cwe", "0").split("-")[-1]) if finding.get("cwe") and "CWE" in str(finding.get("cwe")) else 0,
                "cvssv3": finding.get("cvss", ""),
                "mitigation": finding.get("recommendation", ""),
                "references": finding.get("references", ""),
                "active": True,
                "verified": False,
                "false_p": False,
                "duplicate": False,
            }
            dojo_findings.append(dojo_finding)

        return dojo_findings

    def export_json(self, findings: List[Dict[str, Any]]) -> Dict[str, Any]:
        dojo_findings = self.generate_findings(findings)
        return {
            "status": "ok",
            "engine": "defectdojo_exporter",
            "total_findings": len(dojo_findings),
            "findings": dojo_findings[:20],
        }

class GitHubIssuesExporter:
    """GitHub Issues exporter."""

    def generate_issues(self, findings: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        issues = []
        for finding in findings[:50]:
            severity = finding.get("severity", "MEDIUM")
            issue = {
                "title": f"[{severity}] {finding.get('type','Vuln')} in {finding.get('file','unknown')}",
                "body": f"""## {finding.get('type','Vulnerability')}

**Severity:** {severity}
**File:** `{finding.get('file','unknown')}:{finding.get('line','')}`
**CWE:** {finding.get('cwe','N/A')}

### Description
{finding.get('description','')}

### Recommendation
{finding.get('recommendation','')}

### Evidence
```
{finding.get('evidence', {}).get('code','') if isinstance(finding.get('evidence'), dict) else ''[:500]}
```

*Generated by r3con v7.0*
""",
                "labels": ["security", "r3con", severity.lower(), finding.get("type","").lower().replace(" ", "-")[:20]],
            }
            issues.append(issue)
        return issues

class MITRENavigatorExporter:
    """MITRE ATT&CK Navigator exporter."""

    def generate_layer(self, findings: List[Dict[str, Any]]) -> Dict[str, Any]:
        """Generate ATT&CK Navigator layer JSON."""
        techniques = {}

        for finding in findings:
            mitre = finding.get("mitre", []) or finding.get("attack_mapping", {})
            if isinstance(mitre, dict):
                # From behavior analyzer
                for cat, techs in mitre.items():
                    for tech in techs:
                        # Extract technique ID like T1055
                        import re
                        match = re.search(r"T\d+(?:\.\d+)?", tech)
                        if match:
                            tid = match.group(0)
                            if tid not in techniques:
                                techniques[tid] = {"count": 0, "findings": []}
                            techniques[tid]["count"] += 1
                            techniques[tid]["findings"].append(finding.get("type",""))
            elif isinstance(mitre, list):
                for tech in mitre:
                    import re
                    match = re.search(r"T\d+(?:\.\d+)?", str(tech))
                    if match:
                        tid = match.group(0)
                        if tid not in techniques:
                            techniques[tid] = {"count": 0, "findings": []}
                        techniques[tid]["count"] += 1

        # Build layer
        layer = {
            "name": "r3con v7.0 - Threat Analysis",
            "versions": {"attack": "13", "navigator": "4.8.0", "layer": "4.4"},
            "domain": "enterprise-attack",
            "description": f"Generated from {len(findings)} findings",
            "techniques": [],
        }

        for tid, data in techniques.items():
            score = min(data["count"] * 20, 100)
            color = "#ff0000" if score >= 60 else "#ff8000" if score >= 30 else "#ffff00" if score >= 10 else "#ffffff"
            layer["techniques"].append({
                "techniqueID": tid,
                "score": score,
                "color": color,
                "comment": f"{data['count']} findings: {', '.join(data['findings'][:3])}",
                "enabled": True,
                "showSubtechniques": True,
            })

        return {
            "status": "ok",
            "engine": "mitre_navigator",
            "technique_count": len(techniques),
            "layer": layer,
        }
