"""
r3con - Report Generator
Generates MD, HTML, JSON reports.
"""

import json
from datetime import datetime
from pathlib import Path

REPORTS_DIR = Path.home() / ".r3con" / "reports"

SEV_COLORS = {
    "CRITICAL": "#dc2626", "HIGH": "#ea580c",
    "MED": "#ca8a04", "MEDIUM": "#ca8a04",
    "LOW": "#16a34a", "INFO": "#2563eb"
}
SEV_ORDER = ["CRITICAL","HIGH","MED","MEDIUM","LOW","INFO"]


class ReportGenerator:
    def __init__(self):
        REPORTS_DIR.mkdir(parents=True, exist_ok=True)

    def generate(self, data: dict, fmt: str = "md") -> str:
        ts       = datetime.now().strftime("%Y%m%d_%H%M%S")
        rtype    = data.get("type", "report")
        filename = REPORTS_DIR / f"r3con_{rtype}_{ts}.{fmt}"

        if fmt == "html":
            content = self._render_html(data)
        elif fmt == "json":
            content = json.dumps(data, indent=2, default=str)
        else:
            content = self._render_markdown(data)

        filename.write_text(content)
        return str(filename)

    def _render_markdown(self, data: dict) -> str:
        target   = data.get("source", data.get("binary",
                   data.get("directory", data.get("target", "N/A"))))
        findings = data.get("findings", [])
        lines    = [
            f"# r3con Report — {data.get('type','').upper()}",
            f"**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M')}  ",
            f"**Target:** `{target}`  ",
            f"**Findings:** {len(findings)}",
            "", "---", "",
        ]
        if findings:
            lines.append("## Findings\n")
            sorted_f = sorted(findings,
                key=lambda x: SEV_ORDER.index(x.get("severity","INFO"))
                if x.get("severity","INFO") in SEV_ORDER else 99)
            for f in sorted_f:
                sev  = f.get("severity","INFO")
                loc  = ""
                if f.get("file"):
                    loc += f"`{Path(f['file']).name}` "
                if f.get("line"):
                    loc += f"line {f['line']}"
                lines += [
                    f"### [{sev}] {f.get('type','')}",
                    f"**Location:** {loc or 'N/A'}",
                    f"**Description:** {f.get('description','')}",
                    f"**Fix:** {f.get('recommendation','')}",
                    "",
                ]
        if data.get("output"):
            lines += ["## Raw Output", "", "```", data["output"][:3000], "```", ""]
        lines += ["---",
                  "*Generated by r3con v5.0.0*"]
        return "\n".join(lines)

    def _render_html(self, data: dict) -> str:
        target   = data.get("source", data.get("binary",
                   data.get("directory", data.get("target","N/A"))))
        findings = data.get("findings", [])
        fhtml    = ""
        sorted_f = sorted(findings,
            key=lambda x: SEV_ORDER.index(x.get("severity","INFO"))
            if x.get("severity","INFO") in SEV_ORDER else 99)
        for f in sorted_f:
            sev   = f.get("severity","INFO")
            color = SEV_COLORS.get(sev, "#666")
            loc   = ""
            if f.get("file"):
                loc += f"{Path(f['file']).name} "
            if f.get("line"):
                loc += f"L{f['line']}"
            fhtml += f"""
<div style="border-left:4px solid {color};padding:10px 16px;margin:10px 0;
            background:#1a1a2e;border-radius:4px">
  <span style="background:{color};color:#fff;padding:2px 8px;
               border-radius:3px;font-size:11px;font-weight:bold">{sev}</span>
  <strong style="margin-left:8px;color:#e2e8f0">{f.get('type','')}</strong>
  <span style="color:#64748b;font-size:12px;margin-left:8px">{loc}</span>
  <p style="margin:6px 0 4px;color:#94a3b8;font-size:13px">{f.get('description','')}</p>
  <p style="margin:4px 0;color:#4ade80;font-size:12px">↳ {f.get('recommendation','')}</p>
</div>"""
        return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8">
<title>r3con Report — {data.get('type','').upper()}</title>
<style>
  body{{font-family:'Courier New',monospace;background:#0f0f1a;color:#e2e8f0;
       max-width:960px;margin:40px auto;padding:0 24px}}
  h1{{color:#22d3ee;border-bottom:1px solid #1e293b;padding-bottom:8px}}
  .meta{{color:#64748b;font-size:13px;margin-bottom:24px;
         background:#1e293b;padding:12px;border-radius:6px}}
  h2{{color:#7dd3fc;margin-top:32px}}
</style>
</head><body>
<h1>⚡ r3con Report — {data.get('type','').upper()}</h1>
<div class="meta">
  <strong>Target:</strong> {target}<br>
  <strong>Date:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M')}<br>
  <strong>Findings:</strong> {len(findings)}<br>
  <strong>Tool:</strong> r3con v5.0.0
</div>
<h2>Findings</h2>
{fhtml or '<p style="color:#64748b">No findings.</p>'}
<hr style="border-color:#1e293b;margin-top:40px">
<p style="color:#334155;font-size:12px">Generated by r3con v5.0.0</p>
</body></html>"""
